### ISSUE TITLE
Authenticating with Security Keys in V3

### ISSUE THREAD

**Issue by syntag** [f-23/react-native-passkey#41]
Firstly, thanks for maintaining this package. It's exciting to see `3.0.0-beta` released in stable. I am already starting to test it out.

**Is authenticating with security keys (such as YubiKey) on iOS still supported in V3?**
I noticed that `withSecurityKeys` was removed, and it seems to favor passing `authenticatorAttachment ` with `platform: 'cross-platform'` . However, that option is only available for registration (`Passkey.create()`). 

Side question: Are there plans to support security keys on Android in the future?

**Comment by f-23** [comment]
Hi @syntag,

you are right, as of V3 the security key option can be toggled via `authenticatorAttachement`. Since a get request does not have that field it will make security keys mandatory on iOS.

Is this something you would like to see reverted and have manual control over?

**Comment by syntag** [comment]
> Since a get request does not have that field it will make security keys mandatory on iOS.

@f-23 From my testing, only Passkey is prompted natively on `.get()` for iOS. However, this seems to be a regression in V3, as we no longer have control over this. In V2, we could prompt the native security key sign-in.

Another idea is to support security key in the same iOS auth prompt, as suggested here https://github.com/f-23/react-native-passkey/issues/25

**Comment by f-23** [comment]
@syntag I agree, there should be an option to enforce the usage of either security OR platform key. Default should be to use both.

Since the code structure has changed in the meantime I'm not a big fan of the suggested solution in #25.

Alternatively we could expose 2 additional functions like `Passkey.getSecurityKey()` and `Passkey.getPlatformKey()`. 
Same for passkey creation with `Passkey.createSecurityKey()` and `Passkey.createPlatformKey()`.

They will behave the exact same compared to `Passkey.get()` and `Passkey.create()` on Android. 
On iOS the corresponding function would force the usage of either an external or platform authenticator.

**Comment by syntag** [comment]
@f-23 Strong +1 on your idea of exposing separate functions to authenticate with specific methods

**Comment by f-23** [comment]
@syntag This should be resolved in 3.0.0-rc!
